#!/bin/bash
# Development helper script for Fuji project

echo "==========================================="
echo "Welcome to Fuji Development Environment!"
echo "==========================================="

echo ""
echo "Using Dev Containers (both VS Code and CLI):"
echo "  - To install the Dev Container CLI, visit: https://github.com/devcontainers/cli#installation"
echo "  - To start a container: devcontainer up --workspace-folder ."
echo "  - To connect to container: devcontainer exec --workspace-folder . bash"
echo "  - For compose-based container: devcontainer up --config .devcontainer/docker-compose.devcontainer.json --workspace-folder ."
echo ""
echo "Available commands (inside Dev Container):"
echo "  make build            - Build the project in release mode"
echo "  make build-dev        - Build the project in development mode"
echo "  make test             - Run all tests (unit + security)"
echo "  make test-unit        - Run unit tests only"
echo "  make test-security    - Run security tests only"
echo "  make test-integration - Run integration tests (requires docker services)"
echo "  make clean            - Clean build artifacts"
echo "  make fmt              - Format code"
echo "  make clippy           - Run clippy lints"
echo "  make ci               - Run full CI checks locally"
echo "  make install          - Install the project"
echo ""
echo "Additional useful commands:"
echo "  cargo build           - Standard cargo build"
echo "  cargo test            - Standard cargo test"
echo "  cargo run             - Run the application"
echo "  cargo doc --open      - Build and open documentation"
echo ""
echo "For integration testing, make sure the NFS/SMB test services are running."
echo "In the compose-based devcontainer, they are started automatically."
echo "==========================================="